// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_COUNTER_PLUS_ONE = 'HOME_COUNTER_PLUS_ONE';
export const HOME_COUNTER_MINUS_ONE = 'HOME_COUNTER_MINUS_ONE';
export const HOME_RESET_COUNTER = 'HOME_RESET_COUNTER';
export const HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN = 'HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE = 'HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
export const HOME_LOGIN_USER_BEGIN = 'HOME_LOGIN_USER_BEGIN';
export const HOME_LOGIN_USER_SUCCESS = 'HOME_LOGIN_USER_SUCCESS';
export const HOME_LOGIN_USER_FAILURE = 'HOME_LOGIN_USER_FAILURE';
export const HOME_LOGIN_USER_DISMISS_ERROR = 'HOME_LOGIN_USER_DISMISS_ERROR';
