export const COMMON_REQUEST_SEARCH_BEGIN = 'COMMON_REQUEST_SEARCH_BEGIN';
export const COMMON_REQUEST_SEARCH_SUCCESS = 'COMMON_REQUEST_SEARCH_SUCCESS';
export const COMMON_REQUEST_SEARCH_FAILURE = 'COMMON_REQUEST_SEARCH_FAILURE';
export const COMMON_REQUEST_SEARCH_DISMISS_ERROR = 'COMMON_REQUEST_SEARCH_DISMISS_ERROR';
export const COMMON_CLEAR_SEARCH_RESULTS = 'COMMON_CLEAR_SEARCH_RESULTS';
